# Generated by Django 4.2 on 2023-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='John Doe', max_length=100),
        ),
    ]
